### ISSUE TITLE
Citations code not doing full list 

### ISSUE THREAD

**Issue by Jkellaway** [LizzyParkerPannell/Untargeted_metabolomics_workflow#63]
This should list 8, only list one when I run it in R 
`source("https://raw.githubusercontent.com/LizzyParkerPannell/Untargeted_metabolomics_workflow/main/00_workflow_functions.R")`

**Comment by LizzyParkerPannell** [comment]
Hopefully this is sorted now, think it was an issue with the auto-install of packages
