### ISSUE TITLE
Image/example of file locations. 

### ISSUE THREAD

**Issue by Jkellaway** [LizzyParkerPannell/Untargeted_metabolomics_workflow#70]
Hi Lizzy, 
I think there is an issue with people understanding the file locations and where to be working from in steps 4 and 5. I keep on getting questions about why code isn't working for them and it is usually because they've got too many subfolders, or the samplelist.csv or treatments.csv in the wrong place. 
It would probably clear things up to have a screen grabbed example of the lay out of the files. Showing the root folder, the mass up output folders and their contents, and where the metadata files should go. 
I would do this but have no mass UP processed files, and in all honesty am not 100% sure myself. 
Hope that makes sense
James

**Comment by RMGeorgeSheff** [comment]
I've now got some good screenshots we can use for this, I'm happy to try add them via my branch once I'm set up.

Thanks, 

Rachel

**Comment by LizzyParkerPannell** [comment]
Well done for sorting this guy's, I have merged James Prouts pull request so should be live 👍
